name: Build OnePlus Kernels

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:
    inputs:
      make_release:
        description: 'Do you want to create a release?'
        required: true
        type: boolean
        default: false
      ksun_branch:
        description: "Choose KernelSU Next Branch"
        required: true
        type: choice
        options:
          - stable
          - next
        default: next
      android12-5_10_susfs_branch:
        description: "Choose SusFS Branch for android12-5.10"
        type: string
        default: "gki-android12-5.10"
      android13-5_10_susfs_branch:
        description: "Choose SusFS Branch for android13-5.10"
        type: string
        default: "gki-android13-5.10"
      android13-5_15_susfs_branch:
        description: "Choose SusFS Branch for android13-5.15"
        type: string
        default: "gki-android13-5.15"
      android14-5_15_susfs_branch:
        description: "Choose SusFS Branch for android14-5.15"
        type: string
        default: "gki-android14-5.15"
      android14-6_1_susfs_branch:
        description: "Choose SusFS Branch for android14-6.1"
        type: string
        default: "gki-android14-6.1"
      android15-6_6_susfs_branch:
        description: "Choose SusFS Branch for android15-6.6"
        type: string
        default: "gki-android15-6.6"

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F message_thread_id="${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}" \
            -F text="
            🚀 Build started for OnePlus Kernel! 
            📦 *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})
            🗂️ *Branch:* ${{ github.ref_name }}
            ✏️ *Commit:* [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})
            [🔗 View GitHub Run](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }})" \
            -F parse_mode="Markdown"

  build-batch-1:
    name: build-batch-1 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP11
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_11_v.xml
            android_version: android13
            kernel_version: "5.15"
          - model: OP11r
            soc: waipio
            branch: oneplus/sm8475
            manifest: oneplus_11r_v.xml
            android_version: android12
            kernel_version: "5.10"
          - model: OP-OPEN
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_open_v.xml
            android_version: android13
            kernel_version: "5.15"
          - model: OP-ACE-2
            soc: waipio
            branch: oneplus/sm8475
            manifest: oneplus_ace2_v.xml
            android_version: android12
            kernel_version: "5.10"
          - model: OP10t
            soc: waipio
            branch: oneplus/sm8475
            manifest: oneplus_10t_v.xml
            android_version: android12
            kernel_version: "5.10"
          - model: OP10pro
            soc: waipio
            branch: oneplus/sm8450
            manifest: oneplus_10_pro_v.xml
            android_version: android12
            kernel_version: "5.10"
          - model: OP-ACE-2-PRO
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_ace2_pro_v.xml
            android_version: android13
            kernel_version: "5.15"
          - model: OP12r
            soc: kalama
            branch: oneplus/sm8550
            manifest: oneplus_12r_v.xml
            android_version: android13
            kernel_version: "5.15"
    steps:
      - name: Select Appropriate SusFS Branch
        id: get-susfs-branch
        run: |
          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
          case "$KERNEL_STRING" in
            "android12-5.10")
              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch }}"
              ;;
            "android13-5.10")
              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch }}"
              ;;
            "android13-5.15")
              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch }}"
              ;;
            "android14-5.15")
              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch }}"
              ;;
            "android14-6.1")
              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch }}"
              ;;
            "android15-6.6")
              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch }}"
              ;;
            *)
              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
              exit 1
              ;;
          esac
          if [[ -z "$SUSFS_BRANCH" ]]; then
            SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
          fi
          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: ./.github/actions/build-kernel
        with:
          model: ${{ matrix.model }}
          soc: ${{ matrix.soc }}
          branch: ${{ matrix.branch }}
          manifest: ${{ matrix.manifest }}
          android_version: ${{ matrix.android_version }}
          kernel_version: ${{ matrix.kernel_version }}
          ksun_branch: ${{ inputs.ksun_branch }}
          susfs_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}

  build-batch-2:
    name: build-batch-2 (${{ matrix.model }}, ${{ matrix.soc }}, ${{ matrix.branch }}, ${{ matrix.manifest }}, ${{ matrix.android_version }}, ${{ matrix.kernel_version }}, ${{ inputs.ksun_branch }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - model: OP13
            soc: sun
            branch: oneplus/sm8750
            manifest: oneplus_13.xml
            android_version: android15
            kernel_version: "6.6"
          - model: OPAce5Pro
            soc: sun
            branch: oneplus/sm8750
            manifest: oneplus_ace5_pro.xml
            android_version: android15
            kernel_version: "6.6"
          - model: OP12
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus12_v.xml
            android_version: android14
            kernel_version: "6.1"
          - model: OP13r
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus_13r.xml
            android_version: android14
            kernel_version: "6.1"
          - model: OP-ACE-5
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus_ace5.xml
            android_version: android14
            kernel_version: "6.1"
          - model: OP-ACE-3V
            soc: pineapple
            branch: oneplus/sm7675
            manifest: oneplus_ace_3v_v.xml
            android_version: android14
            kernel_version: "6.1"
          - model: OP-NORD-4
            soc: pineapple
            branch: oneplus/sm7675
            manifest: oneplus_nord_4_v.xml
            android_version: android14
            kernel_version: "6.1"
          - model: OP-PAD-2
            soc: pineapple
            branch: oneplus/sm8650
            manifest: oneplus_pad2_v.xml
            android_version: android14
            kernel_version: "6.1"
          - model: OP13S
            soc: sun
            branch: oneplus/sm8750
            manifest: oneplus_13s.xml
            android_version: android15
            kernel_version: "6.6"
    steps:
      - name: Select Appropriate SusFS Branch
        id: get-susfs-branch
        run: |
          KERNEL_STRING="${{ matrix.android_version }}-${{ matrix.kernel_version }}"
          case "$KERNEL_STRING" in
            "android12-5.10")
              SUSFS_BRANCH="${{ inputs.android12-5_10_susfs_branch }}"
              ;;
            "android13-5.10")
              SUSFS_BRANCH="${{ inputs.android13-5_10_susfs_branch }}"
              ;;
            "android13-5.15")
              SUSFS_BRANCH="${{ inputs.android13-5_15_susfs_branch }}"
              ;;
            "android14-5.15")
              SUSFS_BRANCH="${{ inputs.android14-5_15_susfs_branch }}"
              ;;
            "android14-6.1")
              SUSFS_BRANCH="${{ inputs.android14-6_1_susfs_branch }}"
              ;;
            "android15-6.6")
              SUSFS_BRANCH="${{ inputs.android15-6_6_susfs_branch }}"
              ;;
            *)
              echo "Invalid kernel version or unsupported: $KERNEL_STRING"
              exit 1
              ;;
          esac
          if [[ -z "$SUSFS_BRANCH" ]]; then
            SUSFS_BRANCH="gki-${{ matrix.android_version }}-${{ matrix.kernel_version }}"
          fi
          echo "susfs_branch=$SUSFS_BRANCH" >> $GITHUB_OUTPUT

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Kernel
        uses: ./.github/actions/build-kernel
        with:
          model: ${{ matrix.model }}
          soc: ${{ matrix.soc }}
          branch: ${{ matrix.branch }}
          manifest: ${{ matrix.manifest }}
          android_version: ${{ matrix.android_version }}
          kernel_version: ${{ matrix.kernel_version }}
          ksun_branch: ${{ inputs.ksun_branch }}
          susfs_branch: ${{ steps.get-susfs-branch.outputs.susfs_branch }}

  release:
    if: ${{ inputs.make_release }}
    runs-on: ubuntu-latest
    needs:
      - build-batch-1
      - build-batch-2
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RELEASE_NAME: "*TEST BUILD* OnePlus Kernels With KernelSU Next & SUSFS v1.5.9 *TEST BUILD*"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get commit hashes and generate commit URLs
        run: |
          GITLAB_OWNER="simonpunk"
          GITLAB_REPO="susfs4ksu"
          declare -A Branch_MAP=(
            ["gki_android12_5_10"]="gki-android12-5.10"
            ["gki_android13_5_10"]="gki-android13-5.10"
            ["gki_android13_5_15"]="gki-android13-5.15"
            ["gki_android14_5_15"]="gki-android14-5.15"
            ["gki_android14_6_1"]="gki-android14-6.1"
            ["gki_android15_6_6"]="gki-android15-6.6"
          )
          for var_name in "${!BRANCH_MAP[@]}"; do
            branch_name="${BRANCH_MAP[$var_name]}"
            COMMIT_HASH=$(git ls-remote https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO.git refs/heads/$branch_name | awk '{ print $1 }')
            if [[ -n "$COMMIT_HASH" ]]; then
              COMMIT_URL="https://gitlab.com/$GITLAB_OWNER/$GITLAB_REPO/-/commit/$COMMIT_HASH"
              echo "$branch_name Commit: $COMMIT_HASH"
              echo "$branch_name Commit URL: $COMMIT_URL"
              echo "COMMIT_HASH_${var_name}=$COMMIT_HASH" >> "$GITHUB_ENV"
              echo "COMMIT_URL_${var_name}=$COMMIT_URL" >> "$GITHUB_ENV"
            fi
          done

      - name: Get KernelSU Next ref and link
        run: |
          BRANCH="${{ inputs.ksun_branch }}"
          if [[ "$BRANCH" == "stable" ]]; then
            MODE="tag"
          else
            MODE="commit"
          fi
          if [[ "$MODE" == "tag" ]]; then
            ref=$(git ls-remote --tags --sort=-v:refname https://github.com/KernelSU-Next/KernelSU-Next.git | grep -o 'refs/tags/.*' | cut -d/ -f3 | head -n1)
            url="https://github.com/KernelSU-Next/KernelSU-Next/releases/tag/$ref"
          else
            ref=$(git ls-remote https://github.com/KernelSU-Next/KernelSU-Next.git HEAD | awk '{print $1}')
            url="https://github.com/KernelSU-Next/KernelSU-Next/commit/$ref"
          fi
          echo "KSUN_REF=$ref" >> $GITHUB_ENV
          echo "KSUN_URL=$url" >> $GITHUB_ENV

      - name: Generate and Create New Tag
        run: |
          LATEST_TAG=$(gh api repos/${{ github.repository }}/tags --jq '.[0].name')
          if [ -z "$LATEST_TAG" ]; then
            LATEST_TAG="v1.5.9-r0"
          fi
          NEW_TAG=$(echo "$LATEST_TAG" | awk -F'-r' '{suffix=$2; if (!suffix) suffix=0; suffix++; printf "%s-r%d", $1, suffix}')
          echo "New tag: $NEW_TAG"
          echo "NEW_TAG=${NEW_TAG}" >> $GITHUB_ENV
          git tag $NEW_TAG
          git push origin $NEW_TAG

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./downloaded-artifacts

      - name: Set release body
        run: |
          cat << 'EOF' > release_body.md
          KernelSU Next Branch: ${{ inputs.ksun_branch }}
          Current Kernel Tag: ${{ env.NEW_TAG }}

          Features:
          [+] KernelSU-Next
          [+] SUSFS v1.5.9
          [+] Wireguard Support
          [+] Maphide LineageOS Detections
          [+] Futile Maphide for jit-zygote-cache Detections
          [+] Magic Mount Support
          [+] Ptrace message leak fix for kernels < 5.16
          [+] Manual Hooks [scope_min_manual_hooks_v1.4]
          [+] CONFIG_TMPFS_XATTR Support [Mountify Support]
          [+] BBR v1 Support
          [+] HMBIRD scx support for OnePlus 13 & OnePlus Ace 5 Pro

          Module:
          -> https://github.com/sidex15/ksu_module_susfs

          Managers:
          -> KernelSU-Next: https://github.com/KernelSU-Next/KernelSU-Next / https://t.me/ksunext_group

          Commit Hashes (at the time of release):
          -> KernelSU-Next: [${{ env.KSUN_REF }}](${{ env.KSUN_URL }})
          -> SUSFS4KSU:
            -> gki-android12-5.10: [${{ env.COMMIT_HASH_gki_android12_5_10 }}](${{ env.COMMIT_URL_gki_android12_5_10 }})
            -> gki-android13-5.10: [${{ env.COMMIT_HASH_gki_android13_5_10 }}](${{ env.COMMIT_URL_gki_android13_5_10 }})
            -> gki-android13-5.15: [${{ env.COMMIT_HASH_gki_android13_5_15 }}](${{ env.COMMIT_URL_gki_android13_5_15 }})
            -> gki-android14-5.15: [${{ env.COMMIT_HASH_gki_android14_5_15 }}](${{ env.COMMIT_URL_gki_android14_5_15 }})
            -> gki-android14-6.1: [${{ env.COMMIT_HASH_gki_android14_6_1 }}](${{ env.COMMIT_URL_gki_android14_6_1 }})
            -> gki-android15-6.6: [${{ env.COMMIT_HASH_gki_android15_6_6 }}](${{ env.COMMIT_URL_gki_android15_6_6 }})
          EOF

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.NEW_TAG }}
          prerelease: true
          files: ""
          name: ${{ env.RELEASE_NAME }}
          body_path: release_body.md

      - name: Upload Release Assets
        run: |
          for file in ./downloaded-artifacts/*-kernel-*/*; do
            if [ -d "$file" ]; then
              continue
            fi
            echo "Uploading $file..."
            gh release upload ${{ env.NEW_TAG }} "$file"
          done

      - name: Display Files Uploaded
        run: |
          echo "GitHub release created with the following files:"
          ls ./downloaded-artifacts/**/*

      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
            -F chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
            -F message_thread_id="${{ secrets.TELEGRAM_MESSAGE_THREAD_ID }}" \
            -F text="
            🌽 *New OnePlus Kernel Release Uploaded*  
            📦 *Repository:* [${{ github.repository }}](https://github.com/${{ github.repository }})  
            🗂️ *Branch:* ${{ github.ref_name }}  
            ✏️ *Commit:* [${{ github.sha }}](https://github.com/${{ github.repository }}/commit/${{ github.sha }})  
            [🔗 View GitHub Release](https://github.com/${{ github.repository }}/releases/tag/${{ env.NEW_TAG }})" \
            -F parse_mode="Markdown"
